OasisLMF/OasisPlatform

LICENSE

as per #12 , adding the license file as per repository

Creating license file

---

conf.ini
src/model_execution_worker/tasks.py

Reflects changes to MDK to make exposure summary report generation optional.

Add flag to generate exposure summary report

---

Dockerfile.model_worker
requirements-worker.in
tests/integration/api_integration.py
tests/integration/conftest.py

* new `requirments-worker.in`
* Update API tests due to depreciation in PyTest

Split requirments.in between server & worker

---

src/server/oasisapi/analyses/tests/test_analysis_api.py
src/server/oasisapi/portfolios/tests/test_portfolio.py
src/server/oasisapi/settings.py

Fix Datetime string

---

src/server/oasisapi/analyses/serializers.py
src/server/oasisapi/analyses/viewsets.py
src/server/oasisapi/analysis_models/serializers.py
src/server/oasisapi/analysis_models/viewsets.py
src/server/oasisapi/auth/urls.py
src/server/oasisapi/auth/views.py
src/server/oasisapi/data_files/serializers.py
src/server/oasisapi/healthcheck/views.py
src/server/oasisapi/portfolios/serializers.py
src/server/oasisapi/schemas.py
src/server/oasisapi/settings.py
src/server/oasisapi/urls.py

* fix for running `python manage.py generate_swagger swagger.json`
* Add authenticate header to refresh token
* Fix Auth token responses
* Add response schema for healthcheckk
* Set Many=True for DataFiles
* Fix Portfolio file responses
* Rewrite to_representation as class fields
* Remove Body for task triggers on /Analyses

fix swagger spec

---

src/server/oasisapi/analyses/viewsets.py
src/server/oasisapi/analysis_models/viewsets.py
src/server/oasisapi/data_files/viewsets.py
src/server/oasisapi/files/serializers.py
src/server/oasisapi/portfolios/viewsets.py
src/server/oasisapi/schemas.py

Fix file responses

---

src/server/oasisapi/schemas/model_settings.json

See PR https://github.com/OasisLMF/OasisLMF/pull/489 for details

Add update model_settings schema

---

src/server/oasisapi/analyses/tasks.py

Fix for #311 
* Created a base class **LogTaskError** with method a `on_failure` (triggered by celery on errors / exceptions) to update the API when a result processing task fails in the worker-monitor container.

Add error handling for worker monitor tasks

---

conf.ini
src/model_execution_worker/storage_manager.py
src/server/oasisapi/settings.py

`STORAGE_TYPE` must be set to either `local-fs` or `aws-s3`

Fix #284 - explist select for shared-fs

---

src/server/oasisapi/analyses/migrations/0002_analysis_complex_model_data_files.py
src/server/oasisapi/analyses/migrations/0004_analysis_complex_model_data_files.py

Fix/325 migration from 1.1.2

---

docker-compose.yml
redis.docker-compose.yml
requirements-server.in
requirements-server.txt
requirements-worker.in
requirements-worker.txt
requirements.txt
src/conf/celeryconf.py
src/model_execution_worker/tasks.py
src/server/oasisapi/analyses/models.py
src/server/oasisapi/analyses/tasks.py
src/server/oasisapi/queues/utils.py
src/server/oasisapi/routing.py
src/startup_server.sh
src/startup_worker.sh
src/utils/wait-for-it.sh

This only adds support for redis as a a broker. There isn't a unified api for getting the current queues so we will need to add support as we want to support a new broker

made queue status work for reddis

---

jenkins/oasis_platform.groovy

Issue #342 - automate milestone creation

---

src/model_execution_worker/storage_manager.py
src/model_execution_worker/tasks.py

Fix complex_model_data issue in worker

---

requirements-server.txt
requirements.txt
src/model_execution_worker/tasks.py
src/server/oasisapi/analyses/serializers.py
src/server/oasisapi/analyses/tasks.py
src/server/oasisapi/analyses/tests/test_analysis_api.py

#391 - Store keys errors on failed generate inputs API calls 
#375 - Add check for non-null location files to analyses validation
#394 - Pass model_settings.json to generate-oasis-files

Fix/collected issues 1.9.0

---

requirements-server.in
requirements-server.txt
requirements.txt
s3.docker-compose.yml
src/model_execution_worker/tasks.py
src/server/oasisapi/analyses/models.py
src/server/oasisapi/analyses/tasks.py
src/server/oasisapi/analyses/tests/test_analysis_tasks.py
src/server/oasisapi/analysis_models/admin.py
src/server/oasisapi/analysis_models/models.py
src/server/oasisapi/files/views.py
src/server/oasisapi/portfolios/models.py
src/server/oasisapi/settings.py

* #407 - Store analysis_settings.json in output.tar
* #404 - Cleanup dangling files using delete handlers 
* #403 - Task timestamps - not updating on rerun
* Fixed S3 example compose

Fixes for platfrom

---

src/server/oasisapi/schemas/model_settings.json

Update for issues #409 #400
See: https://github.com/OasisLMF/OasisLMF/pull/673

Sync model settings with MDK

---

src/model_execution_worker/tasks.py

Fix Issue #424

---

src/server/oasisapi/schemas/model_settings.json

Issue #438 
PR https://github.com/OasisLMF/OasisLMF/pull/694

Align platform schema with oasislmf

---

requirements-server.txt
requirements.txt

* issue with swagger UI in develop

Swagger ui broken with Django 3.1+

---

Dockerfile.api_server
Dockerfile.model_worker

* Update packages on docker build, this might bite us on build consistency

Upgrade system packages on build

---

src/model_execution_worker/tasks.py

Also needs https://github.com/OasisLMF/OasisLMF/pull/812 in base oasislmf package

Remove run settings copy from celery task (now in oasislmf)

---

requirements-server.txt
requirements.txt

Fix for https://github.com/OasisLMF/OasisPlatform/pull/491

Bump Django to 3.1.8 - CVE-2021-28658

---

CHANGELOG.rst
Dockerfile.api_server
requirements-server.txt
requirements.txt

Update python to 3.8.9 and Django to 3.0.12

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

See https://github.com/OasisLMF/OasisLMF/pull/826

Added Github Templates

---

jenkins/oasis_platform.groovy

See: https://github.com/OasisLMF/OasisLMF/pull/826

Update build script

---

Dockerfile.api_server
Dockerfile.model_worker
requirements.txt

Development packages were incorrectly added to the `server_api` docker image, removed these for [CVE-2021-20270](https://github.com/advisories/GHSA-9w8r-397f-prfh)

Fix clash with requirements files

---

requirements-server.txt

* Fixes CVE-2021-33571 and CVE-2021-33203
> From: [dependabot PR508](https://github.com/OasisLMF/OasisPlatform/pull/508)

Fix/django CVE issues

---

docker-compose.yml
s3.docker-compose.yml

Workaround for issue #515

---

analysis_settings.json
docker/Dockerfile.mvn-build
docs/analysis_settings.json
docs/analysis_settings.xsd
src/server/oasisapi/analyses/tests/test_analysis_api.py
src/server/oasisapi/schemas/analysis_settings.json
src/server/oasisapi/schemas/model_settings.json

https://github.com/OasisLMF/OasisLMF/pull/957

Update JSON schema to match oasislmf 1.23.0

---

docker-compose.yml
kubernetes/charts/oasis-platform/values.yaml
src/model_execution_worker/distributed_tasks.py
src/server/oasisapi/analyses/tasks.py
src/server/oasisapi/settings.py
src/server/oasisapi/urls.py

- [?] Fix status task marked as error  --> seem to be ok?

Fixes for platform 2.0 [WIP] 

---

src/server/oasisapi/schemas/serializers.py

A workaround for to support worker versions of `1.15.x` and older. With the analysis settings schema change from https://github.com/OasisLMF/OasisLMF/pull/957 any workers using the older schema will fail with the newer `analysis_settings.json` format. 
To address this, without patching the older workers, the obsolete fields are copied into the analysis settings file on POST to the API  
```
{
"analysis_tag": "base_example",
"source_tag": "MDK",
"model_name_id": "PiWind",
"model_supplier_id": "OasisLMF",
"number_of_samples": 10,
"gul_threshold": 0,
"model_settings": { },
"gul_summaries": [ .. ],
"il_summaries": [ .. ],
"ri_summaries": [ .. ],
"gul_output": true,
"il_output": true,
"ri_output": true
}
```
```
{
"analysis_tag": "base_example",
"source_tag": "MDK",
"model_name_id": "PiWind", …
```

Add analysis_settings workaround for lts-1.15.x workers

---

src/server/oasisapi/analyses/viewsets.py
src/server/oasisapi/portfolios/viewsets.py

See issue https://github.com/OasisLMF/OasisPlatform/issues/589
[example_schema_fix.zip](https://github.com/OasisLMF/OasisPlatform/files/7904909/example_schema_fix.zip)

Fix schema so analysis & portfolios are type array

---

src/server/oasisapi/schemas/analysis_settings.json
src/server/oasisapi/schemas/model_settings.json

... Release notes description / summary
... Any text between these two tags will be automatically pulled into the platform release notes

Update schema to match with oasislmf==1.25.0

---

kubernetes/charts/oasis-models/templates/model_registration_job.yaml
kubernetes/charts/oasis-models/values.yaml
kubernetes/charts/oasis-platform/Chart.lock
kubernetes/charts/oasis-platform/templates/cluster-issuer.yaml
kubernetes/charts/oasis-platform/templates/ingress.yaml
kubernetes/charts/oasis-platform/values.yaml
kubernetes/scripts/api/common.sh
kubernetes/scripts/k8s/host_volume_shell.sh
kubernetes/scripts/k8s/upload_piwind_model_data.sh

Changes to support Azure deployment.

Kubernetes updates to support Azure deployment

---

src/model_execution_worker/distributed_tasks.py
src/model_execution_worker/storage_manager.py

Fixed issue with loading custom lookup in worker image

Lookup fixes for non-piwind models

---

kubernetes/worker-controller/src/oasis_websocket.py

Changed the exception handling for the web socket

Improved web socket error handling in worker controller

---

requirements-server.txt

Fix needed for security issues CVE-2022-28346, CVE-2022-28347

Fix CVE-2022-28346, CVE-2022-28347

---

requirements.txt
src/server/oasisapi/schemas/analysis_settings.json

* linked to feature backport https://github.com/OasisLMF/OasisLMF/pull/1052

Update schema for parquet output files

---

src/server/oasisapi/analysis_models/viewsets.py

* https://github.com/OasisLMF/OasisPlatform/issues/647

Fix missing kwarg

---

Dockerfile.model_worker
Dockerfile.model_worker_debian
docker-compose.yml
src/model_execution_worker/distributed_tasks.py
src/server/oasisapi/analyses/tasks.py

* Fixed logging on a per task basis https://github.com/OasisLMF/OasisPlatform/issues/625
* Fixed timestamps https://github.com/OasisLMF/OasisPlatform/issues/635
* Fixed issue loading the `model_settings.json` file in worker

Fixes for work sub-tasks 

---

Dockerfile.api_server
requirements-server.in
requirements-server.txt
src/server/oasisapi/settings.py
src/server/oasisapi/wsgi.py
wsgi/run-wsgi.sh

* Fixed by switching Gateway interface

Switch from daphne to gunicorn

---

requirements-server.txt

* fix needed for  CVE-2022-36359

Update Django for CVE-2022-36359

---

requirements-server.txt
requirements-worker.txt
requirements.txt
update-packages.sh

* Update Pinned python packages

 CVE fixes 1.26.x

---

.github/workflows/build-docker.yml
.github/workflows/build-images.yml
.github/workflows/build-schema.yml
.github/workflows/publish.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-piwind.yml
.github/workflows/test-python.yml
README.md
scripts/find_release.sh
scripts/requirments-changelog.txt
scripts/update-changelog.py
scripts/update-requirements.py

* Added repo scanning / reporting
* Added image tests using piwind and pytest-docker-compose 
* Image build workflow 
* publish workflow 
* Python unittest workflow 
> **Note:** some scripts are failing due to changes needed in the code base. These are either vulnerability fixes or adjustments to the python unit tests. Fixes for these are not included to make merging across multiple version branches easier (backports / Oasis Kubernetes)  
- Auto-update requirments 
- OasisEvaluation update script
- Update docs workflow

Github actions CI/CD update

---

src/server/oasisapi/settings.py

This might cause issues if a model is using https://github.com/OasisLMF/OasisLMF/pull/1222 Disable for the moment

Set Validation on Upload to false

---

requirements-server.txt
requirements-worker.txt
requirements.txt
scripts/update-packages.sh

* Oasislmf to 1.23.16
* cryptography 39.0.1, for [CVE-2023-23931](https://avd.aquasec.com/nvd/cve-2023-23931) [CVE-2023-0286](https://avd.aquasec.com/nvd/cve-2023-0286)

Update Python packages (1.23)

---

requirements-server.txt
requirements-worker.txt
requirements.txt
scripts/update-packages.sh

* Oasislmf to 1.26.6
* cryptography 39.0.1, for [CVE-2023-23931](https://avd.aquasec.com/nvd/cve-2023-23931) [CVE-2023-0286](https://avd.aquasec.com/nvd/cve-2023-0286)

Update python pkg (1.26)

---

requirements-server.txt
requirements-worker.txt
requirements.txt
src/server/oasisapi/files/views.py
src/server/oasisapi/portfolios/tests/test_portfolio.py

* https://github.com/OasisLMF/ODS_OpenExposureData/issues/132
* Fixed unit tests for ods-tools==3.0.2 
* Don't use ods-tools for switching between `csv <-> parquet`

Set ods-tools 3.0.2

---

src/server/oasisapi/schemas/model_settings.json

* Release of Platform 1.27.x is missing a schema update from https://github.com/OasisLMF/OasisLMF/pull/1058

Align with branch backports/1.27.x

---

.github/workflows/build-schema.yml

* Github actions fix for schema build workflow

Fix schema build workflow

---

kubernetes/charts/oasis-platform/values.yaml
requirements-server.txt
requirements-worker.txt
requirements.txt
scripts/update-packages.sh
src/model_execution_worker/distributed_tasks.py

* Update python packages for release 2.1.1

Update Python packages for v2.1.1

---

src/server/oasisapi/files/models.py
src/server/oasisapi/files/serializers.py
src/server/oasisapi/files/views.py
src/server/oasisapi/portfolios/models.py
src/server/oasisapi/portfolios/tests/test_portfolio.py

Update server code to use https://github.com/OasisLMF/ODS_Tools/pull/19

Feature/ods read from stream Plat2

---

scripts/update-changelog.py

* only check the commit message title for linked PR numbers

Fix bug in release note build script

---

.github/workflows/scan-external.yml

Limit external image scans to release PRs

---

.github/workflows/build-images.yml
.github/workflows/build-schema.yml
.github/workflows/project-PR.yml
.github/workflows/project-issue.yml
.github/workflows/publish.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
.github/workflows/version.yml
scripts/build-maven.sh
scripts/deploy.sh
scripts/find_latest.sh
scripts/find_release.sh
scripts/imagesize.sh
scripts/remove_workflow_runs.sh
scripts/requirments-changelog.txt
scripts/runtests.sh
scripts/update-changelog.py
scripts/update-packages.sh
scripts/update-requirements.py

Ci update 1.15

---

.github/workflows/build-images.yml
.github/workflows/build-schema.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
.github/workflows/version.yml
scripts/find_latest.sh

CI update for 1.26

---

.github/workflows/update-python.yml
scripts/update-packages.sh

Add workflow to update requirment files

---

requirements-server.in
requirements-server.txt
requirements-worker.in
requirements-worker.txt
requirements.txt
src/server/oasisapi/auth/tests/fakes.py

* Switch from `psycopg2` to `psycopg2-binary`
* Fixed issue in test imports

Fixes for package updates in 1.15.27

---

Dockerfile.api_server

* Switch base server image  base from  `python:3.9.5-alpine3.13` to `ubuntu:22.04`

Switch docker image from base python:3.9.5-alpine3.13 to ubuntu:22.04

---

.github/workflows/build-images.yml
requirements-server.in
requirements-server.txt
requirements-worker.in
requirements-worker.txt
requirements.txt
scripts/update-packages.sh

* Downgraded `cryptography` and limited CVE scans to `CRITICAL`. For server security improvements upgrade to a `1.23.x` release or later  
* Fix work build issues

Fix 1.15 build issues

---

src/server/oasisapi/analyses/tasks.py

* Fixed issue where Model registration is not retried on S3 bucket error

Fix model reg retry on S3 exception

---

kubernetes/charts/README.md
kubernetes/charts/oasis-platform/templates/oasis_server.yaml
kubernetes/charts/oasis-platform/values.yaml
src/model_execution_worker/distributed_tasks.py
src/startup_worker.sh

- Document how to _not_ deploy the demo PiWind model.
- Pass environment variables from platform values file to API server.
- Support extra arguments on the celery worker via environment variables from the models values file.
- Deduplicate CSV files after merging.
- Merge files using an exact filename match to avoid mangling different files with similar names.

Miscellaneous platform 2 improvements

---

.github/workflows/update-python.yml
scripts/update-packages.sh

* Update python workflow has input field to select packages for CVE fixes

Add option to select packages to update in workflow

---

requirements-server.txt
requirements.txt

Updated Package Requirements: 'django==3.2.19'

---

requirements-server.txt
requirements-worker.txt
requirements.txt
scripts/update-packages.sh

* ods-tools==3.0.7 is required for fixing https://github.com/OasisLMF/OasisPlatform/issues/829

Update packags for release 1.27.4

---

kubernetes/charts/oasis-platform/values.yaml

Updated `postgres`, `mysql`, `keycloak` and `redis` for latest security fixes

Update external docker images

---

docker-compose.yml
requirements-server.in
requirements-server.txt
requirements-worker.txt
requirements.txt

* Updated sqlparse to 0.4.4 for CVE
* Update pymysql to 1.1.0 and pin mysqlclient<=2.1.1,  fix for server build issue

Fix CVE-2023-30608

---

docker-compose.yml
scripts/deploy.sh
src/model_execution_worker/tasks.py
src/server/oasisapi/analyses/models.py
src/server/oasisapi/analyses/task_controller.py
src/server/oasisapi/analyses/tasks.py
src/server/oasisapi/analyses/tests/test_analysis_model.py
src/server/oasisapi/analyses/viewsets.py

> Rebased from https://github.com/OasisLMF/OasisPlatform/pull/585 and merged with changes in https://github.com/OasisLMF/OasisPlatform/pull/778
...

Generate input and run

---

.github/workflows/build-schema.yml
.github/workflows/publish.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
README.md
requirements-server.in
requirements-server.txt
requirements.txt

Update CI 1.27

---

.github/workflows/build-schema.yml
.github/workflows/publish.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
README.md
requirements-server.in
requirements-server.txt
requirements.txt

Update CI 1.23

---

.github/workflows/build-schema.yml
.github/workflows/publish.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
README.md
requirements-server.in
requirements-server.txt
requirements.txt

Update CI 1.26

---

requirements-server.txt
requirements-worker.txt
requirements.txt

* Update Python packages to fix CVE-2023-38325

Fix cryptography CVE-2023-38325 - platform 1  

---

kubernetes/worker-controller/requirements.txt
requirements-server.txt
requirements-worker.txt
requirements.txt

* Update Python packages to fix CVE-2023-38325

Fix cryptography CVE-2023-38325 - platform 2

---

scripts/update-changelog.py

* FIx for ods-tools changelog builder

Fix ods-tools changelog call

---

.github/workflows/build-schema.yml
.github/workflows/publish.yml
.github/workflows/scan-external.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml

Fix actions scripts for stable/2.1.x

---

docker-compose.yml
kubernetes/worker-controller/src/autoscaler.py
scripts/deploy.sh
scripts/minikube-deploy.sh
src/server/oasisapi/analyses/serializers.py
src/server/oasisapi/queues/consumers.py
src/server/oasisapi/queues/serializers.py
src/server/oasisapi/queues/utils.py
src/server/oasisapi/schemas/serializers.py

* Fixed Queue total sub-task count 
* Fixed swagger schema in `/v1/queue-status/` and `/v1/analyses/`
* Removed workaround for older AutoBan issue (not closing WS on error)

Collected Websocket fixes 

---

kubernetes/worker-controller/src/autoscaler_rules.py

Correct error in worker-controller `UnboundLocalError : local variable 'worker_count_max' referenced before assignment`

Fix worker_count_max assigment

---

scripts/update-changelog.py

* Fixed link to ODS Tools in changelog

Updating link for ODS Tools in changelog/release notes #920

---

docker-compose.yml
kubernetes/charts/oasis-platform/templates/oasis.yaml
kubernetes/charts/oasis-platform/values.yaml

Fixed issue that causes the UI to fail find the API. Caused by update to Platform adding both `v1` and `v2` API to the server

Fix OasisUI connection to API 

---

requirements-server.txt
requirements-worker.txt
requirements.txt

* oasislmf==1.28.5
* ods-tools==3.1.4

Updated Package Requirements: oasislmf==1.28.5 ods-tools==3.1.4

---

src/model_execution_worker/distributed_tasks.py
src/server/oasisapi/analyses/models.py
src/server/oasisapi/analyses/v2_api/task_controller.py
src/server/oasisapi/analyses/v2_api/tasks.py
src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py
src/server/oasisapi/analysis_models/models.py
src/server/oasisapi/data_files/models.py
src/server/oasisapi/files/models.py
src/server/oasisapi/portfolios/models.py

Corrected error when running both **generate inputs** and **generate losses**  from a single endpoint `/v2/analyses/{id}/generate_and_run/`

Fixed generate and run endpoint 

---

src/model_execution_worker/distributed_tasks.py

The sub-task **generate_losses_output** will now call ` OasisManager().post_analysis( .. )` if option `post_analysis_module` is set in **oasislmf.json**

Added post analysis hook call before returning outputs (v2 workers) 

---

Dockerfile.api_server

* Fix https://github.com/OasisLMF/OasisPlatform/issues/961

Remove pip from 2nd stage server build

---

kubernetes/charts/oasis-models/resources/model_registration.sh

* Fixed issue when loading `v1` models into the kubernetes Platform

Fix model registration script for v1 workers 

---

requirements-server.txt
requirements-worker.txt
requirements.txt

```
┌─────────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────────────┬─────────────────────────────────────────────────────────────┐
│         Library         │ Vulnerability  │ Severity │ Status │ Installed Version │     Fixed Version     │                            Title                            │
├─────────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────────────┼─────────────────────────────────────────────────────────────┤
│ Django (METADATA)       │ CVE-2023-46695 │ HIGH     │ fixed  │ 3.2.20            │ 3.2.23, 4.1.13, 4.2.7 │ python-django: Potential denial of service vulnerability in │
│                         │                │          │        │                   │                       │ …
```

Fixed CVE issues 1.27.8

---

requirements-server.txt
requirements-worker.txt
requirements.txt

```
┌─────────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│         Library         │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                            │
├─────────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ cryptography (METADATA) │ CVE-2023-50782 │ HIGH     │ fixed  │ 41.0.6            │ 42.0.0        │ python-cryptography: Bleichenbacher timing oracle attack   │
│                         │                │          │        │                   │               │ against RSA decryption - incomplete fix for... …
```

Fixed CVE issues 1.28.8

---

.github/workflows/build-schema.yml
.github/workflows/scan.yml
.github/workflows/test-images.yml
.github/workflows/test-python.yml
Dockerfile.model_worker
Dockerfile.model_worker_debian
src/model_execution_worker/tasks.py
src/model_execution_worker/utils.py
tests/test_tasks.py

* Fixed input generation logs lost on OOM  - [#798](https://github.com/OasisLMF/OasisPlatform/issues/798)

 Logging fixes for workers  (#994) - 1.28

---

src/utils/plat2-migration-helper.sh

Fixed migration helper script which fixes DB migration issues from Platform `2.1.3` -> `2.3.x`

Fix migration helper script

---

compose/debug.docker-compose.yml
docker-compose.yml
kubernetes/worker-controller/requirements.txt
requirements-server.txt
requirements-worker.txt
requirements.txt
scripts/deploy.sh

The default file `docker-compose.yml` has all debugging settings removed, instead these are now in `compose/debug.docker-compose.yml`

Docker compose, removed debugging options from default 

---

src/model_execution_worker/tests/test_tasks.py

Fix failing unittest in release branch 2.3.5

---

.github/workflows/test-images.yml
src/server/oasisapi/analyses/v2_api/tasks.py

* Added missing backwards compatibility check to CI (test last stable `2.3.x` worker with current branch) 
* Fixed Issue https://github.com/OasisLMF/OasisPlatform/issues/1052

Add stable/2.3.x to compatibility checks and fixed V2 worker monitor issue

---

src/model_execution_worker/tasks.py

Fixed logger to show full trace when a V1 worker raises an exception

FIx missing exception trace in V1 workers 

---

requirements-worker.txt
requirements.txt

Updated Package Requirements: fiona==1.10b1 for CVE-2023-45853 & CVE-2020-14152

Fixed CVEs from fiona package

---

requirements-worker.txt
requirements.txt

Updated Package Requirements: fiona==1.10b1 for CVE-2023-45853 & CVE-2020-14152

 Fixed CVEs from fiona package (backport)

---

requirements-server.txt
requirements.txt

Updated Package Requirements: twisted==24.7.0rc1

---

docker-compose.yml

Fix docker compose UI

---

scripts/deploy.sh
src/model_execution_worker/tasks.py

Fix backported version of v1 gen log storage

---

requirements-server.txt
requirements-worker.txt
requirements.txt

Updated Package Requirements

---

src/server/oasisapi/analysis_models/v1_api/tests/test_analysis_model.py
src/server/oasisapi/analysis_models/v2_api/tests/test_analysis_model.py
src/server/oasisapi/portfolios/models.py
src/server/oasisapi/portfolios/v1_api/tests/test_portfolio.py
src/server/oasisapi/portfolios/v2_api/tests/test_portfolio.py

See: https://github.com/OasisLMF/ODS_Tools/issues/174

Workaround for ods tools issue  #174

---

src/server/oasisapi/analysis_models/v1_api/tests/test_analysis_model.py
src/server/oasisapi/analysis_models/v2_api/tests/test_analysis_model.py

Update expected validation errors for ods-tools 4.0.1

---

requirements-server.in
requirements-server.txt
requirements.txt

Pin drf-yasg package

---

kubernetes/worker-controller/Dockerfile

* Updated base image to alpine:3.20 and fixed 'pip error'

Fix worker controller build error

---

Dockerfile.model_worker_debian

* Update base deb image to p3.12 (same as default)

Update base deb image to p3.12

---

.github/workflows/minikube-cicd.yml
scripts/get-minikube-logs.sh

* Added Helm deployment testing
* Added an Oasis api run test for the Helm charts

Minikube CI/CD

---

src/model_execution_worker/utils.py

Fix so that the `user-data`  dir is corrected loaded with data files if any are attached to an analyses

Fix User-data file loading 

---

kubernetes/worker-controller/src/autoscaler.py
src/server/oasisapi/analyses/apps.py
src/server/oasisapi/analyses/models.py
src/server/oasisapi/analyses/v1_api/tests/test_analysis_model.py
src/server/oasisapi/analyses/v2_api/signal_receivers.py
src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py
src/server/oasisapi/queues/consumers.py
src/server/oasisapi/signals.py

* See issue #1185
* Alerts for end of any analysis run to update number of workers

Alerts on completion of analysis (Issue #1185)

---

kubernetes/worker-controller/src/autoscaler.py
src/server/oasisapi/analyses/v2_api/utils.py

Adding an option for null settings due to db issue

Option for null

---

src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py

Fixed test

---

requirements-server.txt
requirements-worker.txt
requirements.txt

Fixes https://github.com/OasisLMF/OasisPlatform/issues/1238 configuration issue caused S3 on EC2 instances to connect as anon

Updated Package Requirements: oasis-data-manager==0.1.5

---

src/model_execution_worker/tasks.py

Fix for https://github.com/OasisLMF/OasisPlatform/issues/1233

Fix for V1 generate_inputs without settings file.

---

.github/workflows/test-images.yml
compose/mysql.docker-compose.yml
src/server/oasisapi/settings/base.py

* Added checks for running with MySQL DB https://github.com/OasisLMF/OasisPiWind/pull/196
* Fixed DB connection settings for MySQL

Fixed mysql DB settings
