- conf.ini
- src/conf/iniconf.py
- src/server/oasisapi/auth/serializers.py
- src/server/oasisapi/auth/tests/test_jwt.py
- src/server/oasisapi/settings.py
* Default Value increased to `days=2`
* New setting added to conf.ini `TOKEN_REFRESH_LIFETIME` it takes a list of comma delimited values as args to
https://docs.python.org/3/library/datetime.html#datetime.timedelta
```
TOKEN_ACCESS_LIFETIME = minutes=1, hours=1, days=1, weeks=1
```
* added `TOKEN_REFRESH_ROTATE` which returns a new refresh token when receiving a POST to `/refresh_token/`
The Previous refresh token is then black listed
* New setting added to conf.ini `TOKEN_ACCESS_LIFETIME` it accepts same types of args as `TOKEN_REFRESH_LIFETIME`
* the **expires_in** field from both `/refresh_token/` and `/access_token/` is set to the access_token expire time
> Extend token settings in conf.ini

- src/server/oasisapi/schemas/model_settings.json
example new sections:
```
"string_parameters":[
{   
"name": "option_name",
"desc": "Option for X, Y or Z",
"default": "some_string"
}   
],  
"list_parameters":[
{   
"name": "option_list",
"desc": "list is for A or B",
"default": ["str1", "str2"]
}   
],  
"dictionary_parameters":[ 
{   
"name": "dictionary_option",
"desc": "this Stores .. for ... etc",
"default": {"k1":"v1", "k2":"v2"}
}   
],  
```
> Add string, list and dict params to model settings schema

- src/conf/celeryconf.py
- src/startup_worker.sh
Fix for issue #387  - Prevent workers from reserving more than 1 task in advance: 
https://docs.celeryproject.org/en/latest/userguide/optimizing.html#reserve-one-task-at-a-time
> Disable task prefetch in worker - blocks idle workers from executing

- src/server/oasisapi/schemas/analysis_settings.json
- src/server/oasisapi/schemas/model_settings.json
Missed JSON schema update for Oasislmf changes: 
* Added return periods option to `analysis_settings.json` [updated-schema.zip](https://github.com/OasisLMF/OasisPlatform/files/5830997/updated-schema.zip)
> Set JSON schema's to be inline with oasislmf

- src/server/oasisapi/analyses/tasks.py
- src/server/oasisapi/portfolios/serializers.py
Possible fix for #455 using: [S3.Object.wait_until_exists()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=query#S3.Object.wait_until_exists)
> call S3 object waiter after invoking copy

- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/tests/test_analysis_api.py
- src/server/oasisapi/analyses/tests/test_analysis_model.py
- src/server/oasisapi/analyses/viewsets.py
Feature for #467
* `​/v1​/analyses​/{id}​/cancel​/` - Cancels either input generation or analysis run depending on the active stage.
* `/v1/analyses/{id}/cancel_analysis_run/` - Cancels a running analysis execution. 
* `/v1/analyses/{id}/cancel_generate_inputs/` - (no change) Cancels inputs generation.
> Add cancel any endpoint

- src/utils/server_bashrc
- src/utils/worker_bashrc
Small update to show the Oasis version number in bash: 
```
oasis-worker(1.16.0) 61103fa3fe30 /home/worker #
oasis-api(1.16.0) 21e303ed9d89 /var/www/oasis #
```
> Update bash promp to show oasis version number

- src/server/oasisapi/portfolios/serializers.py
Fix for connecting S3 files to a new portfolio using the endpoint POST `/v1/portfolios/{id}/storage_links` 
Similar issue as #472 , Affected version (1.16.0)
> Fix issue #498 - error linking S3 object keys

- jenkins/oasis_platform.groovy
Add new CI script parameters 
* `OASISLMF_TAG` 
* `OASISLMF_PREV_TAG` 
* `KTOOLS_TAG` 
* `KTOOLS_PREV_TAG`
These set the repository tags to list change notes between.  All Pull requests between `<KTOOLS_PREV_TAG>`.. `<KTOOLS_TAG>` will be documented in the main release notes. 
If `KTOOLS_PREV_TAG`  == `KTOOLS_TAG` then the notes will skipped over
> Add explicit version tags for auto-release notes

- requirements-server.txt
- requirements-worker.txt
Fixed [CVE-2021-33503](https://github.com/advisories/GHSA-q2q7-5pp4-w6pg) - Catastrophic backtracking in URL authority parser when passed URL containing many @ characters
From: https://github.com/OasisLMF/OasisPlatform/pull/506
> Update urllib3 for CVE-2021-33503

- jenkins/oasis_platform.groovy
- requirements-worker.in
- requirements-worker.txt
In package version `1.18.0` the following python packages for running the builtin lookup are now an optional install. 
```
shapely
geopandas
sklearn
pyarrow
rtree 
cookiecutter
```
Model workers will have these extra packages installed by default (See https://github.com/OasisLMF/OasisLMF/pull/847)
> Build model worker with optional packages

- kubernetes/README.md
- kubernetes/RELEASES.md
- kubernetes/charts/README.md
- kubernetes/charts/oasis-models/templates/workers.yaml
- kubernetes/charts/oasis-monitoring/values.yaml
- kubernetes/charts/oasis-platform/templates/databases.yaml
- kubernetes/charts/oasis-platform/templates/keycloak.yaml
- kubernetes/charts/oasis-platform/templates/oasis.yaml
- kubernetes/charts/oasis-platform/templates/oasis_server.yaml
- kubernetes/charts/oasis-platform/templates/oasis_worker_controller.yaml
- kubernetes/scripts/README.md
- kubernetes/scripts/api/common.sh
- kubernetes/scripts/api/setup_env.sh
- kubernetes/scripts/k8s/host_volume_shell.sh
- kubernetes/scripts/k8s/port-forward.sh
- kubernetes/scripts/k8s/set_ingress_ip.sh
- kubernetes/scripts/k8s/upload_piwind_model_data.sh
- kubernetes/worker-controller/src/cluster_client.py
- kubernetes/worker-controller/src/worker_controller.py
- src/conf/celeryconf.py
- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/tasks.py
- src/server/oasisapi/settings.py
Update the `platform-2.0-analysis-priority_failure-recovery` with the updated change from sprint 5
This spring included mostly testing to make sure it could recover from different failures, for example:
- Randomly failed worker tasks.
- Lost database connection.
- Filesystem error.
- Lost worker for unknown reason.
**Features included:**
* Platform chart improvements:
* RabbitMQ ack timeout disabled (introduced in 3.8.15)
* Platform improvements:
* Enabled retry for worker tasks - A failed task will be run again 2 times.
* Verified that the platform recovers from:
* Randomly failed worker tasks - Each task will be retried 2 times before it is marked as failed.
* Lost database connection - celery will reconnect and retry the task.
* Disk error - Each task will be retried 2 times before it …
> Sprint 6 - Failure recovery - rebased

- requirements-server.txt
- requirements.txt
[CVE-2021-44420](https://nvd.nist.gov/vuln/detail/CVE-2021-44420)  - HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.
> Fix CVE-2021-44420 for Django

- src/server/oasisapi/analyses/viewsets.py
- src/server/oasisapi/portfolios/viewsets.py
The classes `AnalysisListSerializer` and `PortfolioListSerializer` are ReadOnly versions of the standard serializers used only for the GET list methods. This speeds up the responses time, but adds unnecessary objects to the specification. 
This PR overrides these with the standard  `AnalysisSerializer` and `PortfolioSerializer` in the generated OpenAPI schema.
[fixed_openapi-schema.zip](https://github.com/OasisLMF/OasisPlatform/files/7896323/fixed_openapi-schema.zip)
> Fix for API schema generation

- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/task_controller.py
- src/server/oasisapi/analyses/tasks.py
The original method for cancelling worker execution doesn't work with the distributed celery task structure because: 
**1. Celery chains don't have a collective task_id**
The line from here will only work if the first `task_controller` job is still pending. Once that completes there is no `task_id` to revoke the set of pending sub-tasks.    
https://github.com/OasisLMF/OasisPlatform/blob/4335c7fc5d851f4c1a114fbf33cf8745af58ade7/src/server/oasisapi/analyses/models.py#L436-L439
**2.  Using AsyncResult to revoke tasks on a model queue aren't picked up** 
When calling `AsyncResult(sub_task_id).revoke()` the workers on a model queue don't receive the revoke message. 
I'm not sure if this is a bug or a routing problem. The fix is to create a new cancellation task in the `task-controller` …
> Update to fix celery chain cancellation issue

- src/server/oasisapi/settings.py
Posting file upload requests than 2.5MB can trigger a request error, setting `DATA_UPLOAD_MAX_MEMORY_SIZE=None`, disables this check.
> Remove limit for DATA_UPLOAD_MAX_MEMORY_SIZE in Django settings

- src/model_execution_worker/distributed_tasks.py
Complex model lookup fixes caused this, added check to not pass in this argument if no user datafiles are given
```
gument 'user_data_dir'")
Traceback (most recent call last):
File "/root/.local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
ret = task.retry(exc=exc, **retry_kwargs)
File "/root/.local/lib/python3.8/site-packages/celery/app/task.py", line 717, in retry
raise_with_context(exc)
File "/root/.local/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
return task._orig_run(*args, …
```
> Unset "user_data_dir" if no files are given

- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/task_controller.py
- src/server/oasisapi/analyses/tasks.py
- src/server/oasisapi/analysis_models/serializers.py
- src/server/oasisapi/files/serializers.py
- src/server/oasisapi/healthcheck/views.py
- src/server/oasisapi/portfolios/models.py
- src/server/oasisapi/portfolios/viewsets.py
- src/server/oasisapi/settings.py
* ~~Switched setting `PORTFOLIO_PARQUET_STORAGE` to true by default, this means if plain `text/csv` are uploaded, the API will convert these to parquet for storage and execution.~~  reverted until https://github.com/OasisLMF/OasisLMF/issues/1054
is fixed 
* Fixed issue https://github.com/OasisLMF/OasisPlatform/issues/632 a file share mount is no longer needed for the task-controller, the location file length is now read by the server and passed as an integer.
* Fixed issue  https://github.com/OasisLMF/OasisPlatform/issues/627 The platform will now correctly execute exposure files compressed as `zip`, `gzip`, `bzip2` and `parquet`.  However this requires that the **content-type** header is correctly set in the file upload requests. 
* Added validation to enforce the **content-type** header …
> Fix loading and chunking for compressed exposure file

- kubernetes/charts/oasis-platform/templates/_helpers.tpl
- kubernetes/charts/oasis-platform/templates/config_maps.yaml
- kubernetes/charts/oasis-platform/values.yaml
- src/server/oasisapi/settings.py
- src/server/oasisapi/urls.py
> Requires https://github.com/OasisLMF/OasisAzureDeployment/pull/6 to work correctly with [OasisAzureDeployment](https://github.com/OasisLMF/OasisAzureDeployment)
To enable, replace the values in https://github.com/OasisLMF/OasisPlatform/blob/7bb110f919c05a3a4ddf49c3fca669292176d9d4/kubernetes/charts/oasis-platform/values.yaml#L106-L109
with:
```
channel_layer:
type: redis
name: channel-layer
port: 6380
ssl: true 
```
> Add option for ssl redis

- Dockerfile.api_server
- asgi/run-asgi.sh
- docker-compose.yml
- kubernetes/charts/oasis-platform/Chart.yaml
- kubernetes/charts/oasis-platform/templates/_helpers.tpl
- kubernetes/charts/oasis-platform/templates/config_maps.yaml
- kubernetes/charts/oasis-platform/templates/oasis_server.yaml
- kubernetes/charts/oasis-platform/templates/oasis_worker_controller.yaml
- kubernetes/charts/oasis-platform/values.yaml
- requirements-server.in
- requirements-server.txt
- src/server/oasisapi/analyses/management/commands/ws_echo.py
- src/server/oasisapi/asgi.py
- src/server/oasisapi/queues/viewsets.py
- src/server/oasisapi/settings.py
- src/server/oasisapi/urls.py
- src/server/oasisapi/wsgi.py
- wsgi/run-wsgi.sh
**Cause of the problem**
When the oasis server's gateway interface is running in async mode, a feature needed for websocket, HTTP API calls are handled synchronously and block. This causes long lasting http calls, such as file transfers, to cause liveness probe failures which restarts the running server. 
The issue is due to a problem in the Django stack, in the longer term switching to a fully async based REST API would be preferable, unfortunately this currently doesn't look possible due to DRF (Django rest Framework) not supporting async views. For more details on the problem see: https://github.com/django/channels/issues/1587
**Workaround**
The cleanest workaround is running a second deployment of the oasis server, dedicated to running the web-socket using an ASGI (Asynchronous …
> Fix large file download/upload timeout 

- Dockerfile.model_worker
- Dockerfile.model_worker_centos
- Dockerfile.model_worker_debian
Loss analysis will now be marked as failed if either `IL` or `RI` is set in the `analysis_settings.json` but the oasis files are missing
https://github.com/OasisLMF/OasisLMF/pull/1112
> Enable the check-missing-inputs in workers by default

- requirements-server.txt
* fix needed for  CVE-2022-36359
> Update Django for CVE-2022-36359

- kubernetes/charts/oasis-platform/templates/config_maps.yaml
Fixes #718 by ensuring the ssl key is always included in the config maps, even if set to false.
> Always include ssl in configmap

- .github/workflows/build-images.yml
- .github/workflows/scan-external.yml
- .github/workflows/scan.yml
- kubernetes/charts/oasis-platform/resources/oasis-realm.json
- kubernetes/charts/oasis-platform/templates/oasis_server.yaml
- kubernetes/charts/oasis-platform/values.yaml
- requirements-server.txt
- requirements-worker.txt
- requirements.txt
- scripts/update-packages.sh
- src/server/oasisapi/auth/serializers.py
* Fixed token authentication and realm import for keycloak 20.0.3 
* Updated external images to latest versions (RabbitMQ, Postgre, Redis) 
* Fixed Non-root file mount permissions, Added `initContainer` to the Oasis-Server which allows access for default user/group `1000:1000`
* Updated Python Packages 
* Fixed excessive CVE reporting from scans
> Update external image versions 

- src/model_execution_worker/distributed_tasks.py
For files named `events.*`, `occurrence.*` or `ensemble_mapping.*`, take the first file (i.e. assume they are all identical and no merging is required).
For all other csv files, concatenate them.
For all other parquet files, concatenate them respecting indices (i.e. retain the existing indices in the merged output and remove duplicates based on these indices).
> Fixes for merging of distributed input files

- scripts/update-changelog.py
Using `click.Choice` is too restrictive, switching to  `click.STRING` so Github actions can pass in `${{ github.event.repository.name }}` for any Oasislmf repo
> Loosen repository argument in changelog builder 

- src/model_execution_worker/distributed_tasks.py
The generated inputs tar has a copy of the symlink set (or files) loaded into the input generation directory. 
This creates two issues: 
1. There are now two sets user-data files in the loss calc run folder 
2. The unexpected set of symlinks trips up oasislmf's execution causing an loss analysis to fail with  
```
oasislmf.utils.exceptions.OasisException: Error preparing the 'run' directory: [Errno 21] Is a directory: '/tmp/run/analysis-3_losses-1987ce8eb5a74152bc3ed58b82584850/input-data/user-data'
```
> Clear user-data before tar of generated data

- docker/Dockerfile.mvn-build
- kubernetes/charts/oasis-models/templates/workers.yaml
- kubernetes/charts/oasis-platform/values.yaml
- src/model_execution_worker/distributed_tasks.py
* Fixed issue with location file chunking, without re-indexing the location file chunk some supplier lookup classes will drop keys
* Increased liveness probes on worker pods, workers under full load can timeout from celery and restart.
> Plat 2.1.1 fixes

- .github/workflows/publish.yml
* Release `1.15.28` accidentally overrode `model_worker:latest` and `api_server:latest`, added explicit checkbox to select which release should publish using the `latest` tag
> Update publish with checkbox to push images with latest tag

- src/model_execution_worker/distributed_tasks.py
* `str.removesuffix` is not supported in py3.8, replaced with `rstrip`
> Fixed bug in collect keys for debian worker

- compose/traefik.docker-compose.yml
- compose/traefik/config/dynamic.yml
- compose/traefik/config/traefik.yml
An example docker-compose file using [Traefik](https://doc.traefik.io/traefik/providers/docker/) as a reverse proxy for OasisUI.
> Traefik example for OasisPlatform in docker-compose

- src/server/oasisapi/portfolios/serializers.py
> Rebased from https://github.com/OasisLMF/OasisPlatform/pull/682
Fixed the endpoint `/v1/portfolios/{id}/storage_links/` when connecting unregistered blobs (not already in the Django `default_storage` adapter) and connecting the blob to a portfolio as an exposure file.
> Fixed portfolio file linking with Azure Blobs 

- .github/workflows/build-schema.yml
- .github/workflows/publish.yml
- .github/workflows/scan.yml
- .github/workflows/test-images.yml
- .github/workflows/test-python.yml
- README.md
> Update CI 1.15

- src/server/oasisapi/analyses/tests/test_analysis_api.py
- src/server/oasisapi/schemas/serializers.py
Bug added when the analysis settings compatibility mapping (needed for workers 1.15.x) was moved to ods-tools. 
Reverted to the settings validation from platform (1.27.1)
https://github.com/OasisLMF/OasisPlatform/blob/bcc3a28a19ab52ff5582c6c13851996aa74a46fe/src/server/oasisapi/schemas/serializers.py#L207-L220
This stores both older and newer keys in the analysis settings file when its posted to the server.
> revert settings compatibility to older version

- kubernetes/charts/oasis-platform/values.yaml
The Keycloak admin console is broken in version 22, configuration needs a review to fix https://github.com/OasisLMF/OasisPlatform/issues/876 
In the meantime, reverting keycloak to the last working version 21.1.1
> Revert keycloak version to 21.1.1

- src/server/oasisapi/files/serializers.py
- src/server/oasisapi/portfolios/models.py
Fix for issue https://github.com/OasisLMF/OasisPlatform/issues/871 catch and raise exceptions and throw a validation error to return **400 Bad request** instead of **500 Server error.**
> Fix/871 odstools exceptions (Plat1) 

- kubernetes/charts/oasis-monitoring/templates/flower.yaml
Fix **oasis-monitor** chart, deployment fails with `cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
> Fix syntax in flower chart template

- kubernetes/charts/oasis-platform/templates/keycloak.yaml
- requirements-server.txt
- requirements-worker.txt
- requirements.txt
- src/model_execution_worker/distributed_tasks.py
The newer versions of Keycloak switched the environment variable prefix from `KEYCLOAK` to `KC`. This caused the Keycloak server to silently fallback on local `dev-file` data storage which is not persistence across restarts. 
Fixed the Database connection to correctly connect to PostgresSQL. 
> **Reference:** [Keycloak documentation - Configuring the database](https://www.keycloak.org/server/db)
> Fix Keycloak DB connection

- .github/workflows/build-schema.yml
- .github/workflows/scan-external.yml
- .github/workflows/scan.yml
- .github/workflows/test-images.yml
- .github/workflows/test-python_api.yml
- .github/workflows/test-python_worker-controller.yml
- kubernetes/worker-controller/src/autoscaler.py
- kubernetes/worker-controller/src/autoscaler_rules.py
- kubernetes/worker-controller/src/tests/test_autoscaler.py
- kubernetes/worker-controller/src/tests/test_autoscaler_rules.py
- scripts/minikube-deploy.sh
- src/server/oasisapi/queues/serializers.py
- src/server/oasisapi/queues/utils.py
* Set worker-controller to check the queue for a build up of unhandled messages on a worker queue. When messages are detected, Spawn a single worker pod to kick the auto-scaler back into working.  
* Backport worker-controller refactor from https://github.com/OasisLMF/OasisPlatform/pull/931
* Fixed worker-controller unittests
> Fixes for Worker-controller 2.1.3

- src/server/oasisapi/queues/utils.py
Channel connections were not closed on exit of celery queue query, this results in a build up of idle channel connections that eventually causes https://github.com/OasisLMF/OasisPlatform/issues/953
> Fixed AMQP idle channels issues 

- .github/workflows/build-schema.yml
- .github/workflows/publish.yml
- src/server/oasisapi/analyses/v1_api/serializers.py
- src/server/oasisapi/analyses/v2_api/serializers.py
- src/server/oasisapi/analysis_models/v1_api/serializers.py
- src/server/oasisapi/analysis_models/v2_api/serializers.py
- src/server/oasisapi/data_files/v1_api/serializers.py
- src/server/oasisapi/data_files/v2_api/serializers.py
- src/server/oasisapi/portfolios/v1_api/serializers.py
- src/server/oasisapi/portfolios/v2_api/serializers.py
- src/server/oasisapi/queues/serializers.py
- src/server/oasisapi/schemas/serializers.py
- src/server/oasisapi/settings/base.py
- src/server/oasisapi/swagger.py
- src/server/oasisapi/urls.py
* Added nested swagger pages, this clears up the automatic tagging in DRF-YASG, endpoints listed in the version specific specifications are tagged as `[analyses, analysis-task-statuses, data_files, models, portfolios ..]`. However the main specification is still tags as `[v1, v2]`
- `http://<domain>/`, main OpenAPI specification for **API** (all endpoints shown) 
- `http://<domain>/v1/`, OpenAPI specification for **v1** endpoints 
- `http://<domain>/v2/`  OpenAPI specification for **v2** endpoints 
* The new specification files are built via GitHub actions and attached as assets to each release. 
* Renamed serializer `ref_names`. Any clashing names are suffixed with **V1**, for example, the analysis return for the `/v1/analyses/` endpoint is now **AnalysisSerializerV1**, while …
> Split OpenAPI schemas between v1 and v2 versions of the API 

- src/conf/celeryconf.py
- src/model_execution_worker/storage_manager.py
- src/model_execution_worker/tasks.py
Two fixes for platform 1 workers (`1.15.x`, `1.23.x`, `1.27.x`, `1.28.x`) running on azure via kubernetes. 
*  CeleryDB passwords with special characters (like `#`) can crash workers because these are not escaped correctly 
* Workers fail to store results in the shared-fs file mount due to `chmod` causing an exception.
> Fix Azure support for workers (platform 1)

- src/server/oasisapi/swagger.py
- src/server/oasisapi/urls.py
When `SUB_PATH_URL=True`  the server uses a prefix url `api/<version>/<end-point>`. 
Fixed calls from new swagger pagers `http://localhost:8000/api/v1/` and `http://localhost:8000/api/v2/` which dropped the `api` prefix in example calls returning `404`.
> Fix broken swagger calls when SUB_PATH_URL=True 

- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/apps.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/v2_api/signal_receivers.py
- src/server/oasisapi/analyses/v2_api/tasks.py
- src/server/oasisapi/queues/consumers.py
* Added queued analyses objects to  **websocket** output, this is to ensure worker-controller doesn't get into a stuck state 
* Reduced the amount of  **websocket**  messages, sub-task update messages are no longer published. A large number of messages causes instability between the `oasis-websocket` and `worker-controller` pods
* Fixed V1 analysis not showing up in the **websocket** output
> Fixes for websocket stability

- docker-compose.yml
- src/server/oasisapi/queues/utils.py
* Fix for https://github.com/OasisLMF/OasisPlatform/issues/989
> Only use a single channel connect when fetching queue states

- .github/workflows/test-images.yml
- kubernetes/worker-controller/src/oasis_client.py
- src/model_execution_worker/distributed_tasks.py
- src/model_execution_worker/tasks.py
- src/model_execution_worker/tests/test_tasks.py
- src/model_execution_worker/utils.py
- src/server/oasisapi/analyses/v2_api/tasks.py
* Fixed worker monitor failing to handle raised Exceptions - [#993](https://github.com/OasisLMF/OasisPlatform/issues/993)
* Fixed input generation logs lost on OOM  - [#798](https://github.com/OasisLMF/OasisPlatform/issues/798)
* Fixed `oasislmf.json` with `analysis_settings` set causing run errors = [#971](https://github.com/OasisLMF/OasisPlatform/issues/971)
* Fixed missing ktools `run_log_file` not stored in `V2` loss generation runs - [#664](https://github.com/OasisLMF/OasisPlatform/issues/664)
* Fixed Subtask error logs are not available under analysis, all sub-tasks marked as `ERROR` will store their logs in `input_generation_traceback_file` or `run_traceback_file` - [#784](https://github.com/OasisLMF/OasisPlatform/issues/784)
> **Warning:** Keys generation needs [PR …
> Logging fixes for workers 

- .github/workflows/build-schema.yml
- .github/workflows/scan.yml
- .github/workflows/test-images.yml
- .github/workflows/test-python.yml
- Dockerfile.model_worker
- Dockerfile.model_worker_debian
- src/model_execution_worker/tasks.py
- src/model_execution_worker/utils.py
- tests/test_tasks.py
* Fixed input generation logs lost on OOM  - [#798](https://github.com/OasisLMF/OasisPlatform/issues/798)
>  Logging fixes for workers  (#994) - 1.27

- kubernetes/charts/oasis-platform/templates/oasis_server.yaml
Fixed - Django Migration should only happen in one container
> Remove DB migration env on websocket

- src/model_execution_worker/distributed_tasks.py
- src/model_execution_worker/utils.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/v1_api/tasks.py
- src/server/oasisapi/analyses/v2_api/tasks.py
Minor fixes to improve task cancellation
* Skip `cancel_subtasks` when cancellation is called on a `V1` analysis. Shouldn't cause issues if called but is also not needed. 
* Fixed issue marking `V2` analysis as `ERROR` when celery cord reports back a link error with `Task Terminated` 
* Fixed `V1 worker-monitor` throwing an error when trackback is not set.
* Fixed `V1 worker` raising error when removing a temp dir fails.
> Fixes for task Cancellation Handling 

- src/server/oasisapi/data_files/models.py
Fixed issue where the endpoints `/analyses/{id}/data_files/` and `/models/{id}/data_files/` failed with:
```
Exception Type: NoReverseMatch at /api/v2/analyses/{id}/data_files/
Exception Value: Reverse for 'data-file-content' not found. 'data-file-content' is not a valid view function or pattern name.
```
This comes from the the namespace value in **request.version**, which should read `'v2-files'` and not `'v2-analyses'`.
> Fix namespace issue when called from analysis serializer

- src/model_execution_worker/tasks.py
- src/server/oasisapi/analysis_models/v2_api/serializers.py
* Fixed Scaling configuration validation error (Server 500) when model is missing its default `ModelScalingOptions` object  
* Fixed missing `filestore` arg in call to **prepare_complex_model_file_inputs( .. )**
> Minor bug fixes for worker and server

- src/model_execution_worker/tasks.py
- src/model_execution_worker/tests/test_tasks.py
…precated param names
Added missing param compatibility call, this checks for older parameter names in `oasislmf.json` and updates when found.
>  Fixed missing call to param update method - V1 Workers

- kubernetes/charts/oasis-platform/templates/keycloak.yaml
Added option to mount Keycloak certificate (from MS) to support Postgres Flexible server deployments
> Azure Postgres Flexible server support   

- .github/workflows/scan-external.yml
Switched the external image scans to manual only. 
This almost always fails, since external images are out of our control.
>  CI - Disable external docker images scanning 

- requirements-server.txt
- requirements-worker.txt
- requirements.txt
- src/model_execution_worker/tasks.py
- tests/test_tasks.py
Added missing param compatibility call, this checks for older parameter names in `oasislmf.json` and updates when found.
> Backport 1.28.x -  Fixed missing call to param update method - V1 Workers (#1045)

- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/queues/consumers.py
* Fixed issue with auto-scaler send full queue state to web-socket when an analysis is submitted (not a filtered list)
* Fixed bug in pre-analysis hook causing custom oed spec to be removed
> Fix autoscaling ramping down when new analysis run is triggered  

- kubernetes/charts/oasis-platform/templates/keycloak.yaml
Helm chart adjustment for running OasisAzureDeployment with https://github.com/OasisLMF/OasisAzureDeployment/pull/23
> Fix keycloak when running with Postgres Flexible server

- src/server/oasisapi/analyses/v2_api/serializers.py
- src/server/oasisapi/analyses/v2_api/viewsets.py
- src/server/oasisapi/analysis_models/v2_api/serializers.py
- src/server/oasisapi/analysis_models/v2_api/viewsets.py
`Models` and `Analyses` **V2 endpoints** now accept settings json on **POST** and **PATCH** calls via an optional `'settings: { .. json ..}'` field. These are validated before the new object is created,  if valid the settings are loaded into the newly created (or updated) instance. 
```
{
"name": "string",
"portfolio": 1,
"model": 1,
"settings": {
"model_name_id": "PiWind",
"model_supplier_id": "OasisLMF",
"gul_threshold": 0,
"gul_output": true,
"model_settings": {
"event_set": "p",
"event_occurrence_id": "lt"
},
"gul_summaries": [
{"id": 1, "eltcalc": true}
],
"il_output": false,
"il_summaries": [],
"ri_output": 'foo',
"ri_summaries": []
}
}
```
```
{
"supplier_id": "OasisLMF",
"model_id": "PiWind",
"version_id": "ver",
"settings": {  
"model_settings":{
"event_set":{
"name": "Event …
```
> Accept settings JSON on analysis or model creation 

- src/conf/iniconf.py
Fix added - if sections are not set in a workers config file, environment variable will still load correctly.
> Ensure ConfigParser has required sections when not set in conf.ini file

- kubernetes/scripts/api/api.sh
- kubernetes/scripts/api/setup_env.sh
Groups property is being used on:
- portfolios
- models
- data_files
- analyses
But v1 of the API does not return property groups. Only v2 does.
After checking the swagger, updating to v2 seems better than removing groups from the sanitization of the returned body.
Using API v2 for:
- /models/${PIWIND_VERSION}/chunking_configuration
- /models/${PIWIND_VERSION}/scaling_configuration
Version 1 of the API lacks these methods. Using same configs as in the local files next to /meta-data/model_settings.json
> Use version 2 of the API on api ls commands

- src/model_execution_worker/distributed_tasks.py
- src/server/oasisapi/analyses/v2_api/tasks.py
* Celery can fail to log exceptions which are not pickable or json-serializable. Added exception logging within the V2 worker task file in case this happens (workaround). 
* Added check in worker-monitor v2 to make sure the trackback from sub-tasks is not set to `None`
> Fix to handle exceptions which can't be serialized by celery

- src/server/oasisapi/analyses/v2_api/viewsets.py
- src/server/oasisapi/analysis_models/v2_api/serializers.py
- src/server/oasisapi/analysis_models/v2_api/viewsets.py
Corrected the returns from `/analyses/`  and `/model/` so that the settings resources are `settings: <URL-to-file>` and not    `settings: <JSON>`  
**Note:** This is the same behaviour as release prior to   https://github.com/OasisLMF/OasisPlatform/pull/1067
> Fix API spec - return for create & update for 'analyses' and 'model'

- src/model_execution_worker/distributed_tasks.py
Added custom code hooks from https://github.com/OasisLMF/OasisLMF/pull/1524
* pre-analysis (unchanged) - runs in its own sub-task before keys lookup and modifies the exposure files. 
* **post-generation-hook (new)** - runs directly after `write-oasis-files` but before the inputs.tar.gz is created. 
* **pre-losses-hook (new)** - runs after the runs losses directory has been initialized, but before executing an analysis. 
* post-losses-hook (unchanged) - runs after the output calc has run, but before creating the results file `output.tar.gz`
> Added new hooks to v2 workflow 

- src/model_execution_worker/distributed_tasks.py
- src/model_execution_worker/tasks.py
* Fixed log storage for input generation (run_mode=v1). workers now store a copy of run logs in the `input.tar.gz` file. 
* Fixed log storage for input generation (run_mode=v2). Workers copy in each sub-task log file to a `log/` within a the `input.tar.gz` file
* Fixed mismatch between v1 and v2 ktools log stored under `/run_log_file/`,  v2 no longer nests the archive in a `logs` sub-dir.
> Fix log storage in results tar files

- src/model_execution_worker/tasks.py
Needed so that custom hooks are correctly called for workers in run_mode=V1, similar to https://github.com/OasisLMF/OasisPlatform/pull/1087
> Fix params for V1 workers ~ so custom hooks are called

- src/model_execution_worker/distributed_tasks.py
- src/model_execution_worker/tasks.py
Worker storage manager between `main` and `stable/2.3.x` is different, fix needed to work with both
> Relase fix - gen log storage (#1107)

- src/server/oasisapi/analysis_models/v1_api/serializers.py
- src/server/oasisapi/analysis_models/v1_api/viewsets.py
- src/server/oasisapi/analysis_models/v2_api/serializers.py
- src/server/oasisapi/analysis_models/v2_api/viewsets.py
Added the following endpoints to models, `/v1/models/{id}/storage_links/` and `/v2/models/{id}/storage_links/`. 
works in the same way as the other storage_links endpoints on (models and portfolios), returns the real filename or Object Store key of the model settings file. 
**example return** 
```
{
"settings_file": "82cd9b3e16c44954a1ec98be6554440b.json"
}
```
> Added model storage_links endpoint

- kubernetes/charts/oasis-platform/resources/oasis-realm.json
- src/server/oasisapi/oidc/keycloak_auth.py
Issue [#1111](https://github.com/OasisLMF/OasisPlatform/issues/1111) - the users group information wasn't included in the JSON Web Token (JWT). This causes OasisAPI objects to be created without any groups attached.
> Fixed group mapper class in Keyclock realm config

- requirements.txt
- src/model_execution_worker/distributed_tasks.py
> needs applying to `main` branch too
> Fixed pre-analysis exposure files not working in V2 worker runs 

- src/model_execution_worker/tasks.py
- src/server/oasisapi/analyses/models.py
- src/server/oasisapi/analyses/v1_api/serializers.py
- src/server/oasisapi/analyses/v1_api/tests/test_analysis_model.py
- src/server/oasisapi/analyses/v2_api/serializers.py
- src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py
- src/server/oasisapi/portfolios/v1_api/serializers.py
- src/server/oasisapi/portfolios/v1_api/tests/test_portfolio.py
- src/server/oasisapi/portfolios/v2_api/serializers.py
- src/server/oasisapi/portfolios/v2_api/tests/test_portfolio.py
* Only for `run_mode = V1`  allow input generation to work without posting a location.csv file. 
* Update the check in portfolios to allow execution if **Either** a location or an account file is attached.
> Add cybermodels support in the OasisAPI - V1 Only

- src/model_execution_worker/tasks.py
In `run_mode = v1`  the conf.ini `MODEL_SETTINGS_FILE` variable can override the **oasislmf.json**
model_settings path.   This value has been removed from the run_params. its not ONLY used for a workers auto-registration and the only source of the model_settings path is given by the oasislmf config.
> Removed the conf.ini variable MODEL_SETTINGS_FILE from run params

- src/server/oasisapi/settings.py
* Added a fix to Django settings to avoid `permission denied` errors when upload files to azure files
* Fixed 'Network error' when access swagger via an ingress using https
> Add setttings from platform v2 for running the v1.28.x server on azure cloud

- kubernetes/worker-controller/requirements.txt
- requirements-server.txt
- requirements.txt
Issue seems to come from the update to package `drf-yasg==1.21.8` from `drf-yasg==1.21.5`. 
Note: this problem dosn't show on **main** only **stable/2.3.x**
> Fix API schema change, missing description fields 

- Dockerfile.api_server
- Dockerfile.model_worker
- requirements.txt
Moving to ubuntu `24.04` uses a version of python with a stricter package manager. Added an env variable to base image as a workaround. 
```
error: externally-managed-environment                                          
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx …
```
> Fixed pip install on model worker images 

- kubernetes/worker-controller/src/autoscaler.py
* Fixed issue where a analysis run requests is on a V1 queue will be viewed as a waiting V2 analyses. 
This causes the auto-scaling to spin workers up and down.
> Worker controller detects pending V1 task and tries to scale V2 workers 

- src/model_execution_worker/tasks.py
Needed to write the trace to oasis logger, not root celery task logger
> Fixed missing stack trace logging for V1 workers 

- src/server/oasisapi/base_urls.py
- src/server/oasisapi/healthcheck/tests/test_healthcheck.py
- src/server/oasisapi/healthcheck/views.py
if the oasis-server is under load the response time of the celery / DB tests in the heathcheck can cause liveness probes to fail.   
`healthcheck` - shallow test, used to check if the API is responsive 
`healthcheck_connections` - deeper healthcheck which also checks for connections to celery and DB
[example_shallow_healthcheck_loaded.txt](https://github.com/user-attachments/files/20343654/example_shallow_healthcheck_loaded.txt)
[example_deep_healthcheck_overloaded.txt](https://github.com/user-attachments/files/20343656/example_deep_healthcheck_overloaded.txt)
> Split the healthcheck between deep and shallow

- .github/workflows/build-images.yml
- .github/workflows/scan-external.yml
- .github/workflows/scan.yml
fixes the following issue: 
```
Error: CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
```
> update upload to v3

- src/server/oasisapi/analysis_models/models.py
- retrieving analysis settings template causes internal server error due to lack of `_ns_update` method in `SettingsTemplate` but doing this `_ns_update` is not necessary for requests that arrive at `SettingsTemplate`
> fix/analysis settings template `_ns_update`
